[package]
name = "finder"
version = "0.1.3"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
fuzzy-matcher = "0.3.7"
ratatui = "0.29.0"
tokio = { version = "1.43.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
walkdir = "2.5.0"
